# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3

jobs:

  cli:
    name: set base ubuntu environment
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Tune Runner VM
        uses: ./.github/actions/tune-runner-vm

      - name: Detect changed files
        id:   changes
        uses: apache/pulsar-test-infra/paths-filter@master
        with:
          filters: .github/changes-filter.yaml

      - name: Check changed files
        id: check_changes
        run: echo "::set-output name=docs_only::${{ fromJSON(steps.changes.outputs.all_count) == fromJSON(steps.changes.outputs.docs_count) && fromJSON(steps.changes.outputs.docs_count) > 0 }}"

      - name: Cache local Maven repository
        if: ${{ steps.check_changes.outputs.docs_only != 'true' }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/*/*/*
            !~/.m2/repository/org/apache/pulsar
          key: ${{ runner.os }}-m2-dependencies-all-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-dependencies-core-modules-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-m2-dependencies-core-modules-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        if: ${{ steps.check_changes.outputs.docs_only != 'true' }}
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Replace maven's wagon-http version
        if: ${{ steps.check_changes.outputs.docs_only != 'true' }}
        run: sudo ./build/replace_maven-wagon-http-version.sh

      - name: clean disk
        if: ${{ steps.check_changes.outputs.docs_only != 'true' }}
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker images -q) -f
          df -h
      - name: run install by skip tests
        if: ${{ steps.check_changes.outputs.docs_only != 'true' }}
        run: mvn -q -B -fn -ntp clean install #-DskipTests
        
      - name: Upload container logs
        uses: actions/upload-artifact@v2
        if: ${{ cancelled() || failure() }}
        continue-on-error: true
        with:
          name: container-logs
          path: tests/integration/target/container-logs

      - name: Upload surefire-reports
        uses: actions/upload-artifact@v2
        if: ${{ cancelled() || failure() }}
        continue-on-error: true
        with:
          name: surefire-reports
          path: tests/integration/target/surefire-reports
